apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials
  namespace: external-dns
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mikrotik-credentials
    creationPolicy: Owner
  data:
    - secretKey: MIKROTIK_BASEURL
      remoteRef:
        key: mikrotik/creds
        property: baseurl
    - secretKey: MIKROTIK_USERNAME
      remoteRef:
        key: mikrotik/creds
        property: username
    - secretKey: MIKROTIK_PASSWORD
      remoteRef:
        key: mikrotik/creds
        property: password
    - secretKey: MIKROTIK_SKIP_TLS_VERIFY
      remoteRef:
        key: mikrotik/creds
        property: skip_tls_verify
