apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: firefly
    namespace: firefly
spec:
    interval: 30m
    chart:
        spec:
            chart: app-template
            version: "4.5.0"
            sourceRef:
                kind: HelmRepository
                name: bjw-s
                namespace: firefly
    values:
        controllers:
            main:
                containers:
                    main:
                        image:
                            repository: fireflyiii/core
                            tag: version-6.1
                        env:
                            DB_CONNECTION: pgsql
                            DB_HOST: firefly-postgres-rw.firefly.svc.cluster.local
                            DB_PORT: "5432"
                            DB_DATABASE: firefly
                            DB_USERNAME: firefly
                            APP_URL: "https://firefly.k8s.home.lab"
                            TRUSTED_PROXIES: "*"
                            AUTHENTICATION_GUARD: remote_user_guard
                            AUTHENTICATION_GUARD_HEADER: HTTP_X_AUTHENTIK_USERNAME
                            AUTHENTICATION_GUARD_EMAIL: HTTP_X_AUTHENTIK_EMAIL
                        envFrom:
                            - secretRef:
                                  name: firefly-secrets
            redis:
                containers:
                    main:
                        image:
                            repository: valkey/valkey
                            tag: "7.2"
        service:
            main:
                controller: main
                ports:
                    http:
                        port: 8080
            redis:
                controller: redis
                ports:
                    redis:
                        port: 6379
        persistence:
            storage:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: firefly-data
                globalMounts:
                    - path: /var/www/html/storage
