apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    name: main-gateway
    namespace: gateway
spec:
    gatewayClassName: cilium
    listeners:
        - name: http
          protocol: HTTP
          port: 80
          hostname: "*.k8s.home.lab"
          allowedRoutes:
              namespaces:
                  from: All
    addresses:
        - type: IPAddress
          value: "192.168.1.200"
