apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mikrotik-creds
  namespace: external-secrets-system
spec:
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: mikrotik-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mikrotik/creds
        property: username
    - secretKey: password
      remoteRef:
        key: mikrotik/creds
        property: password
