apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnativepg
  namespace: database
spec:
  interval: 1h
  url: https://cloudnative-pg.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.3"
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg
        namespace: database
  values:
    crds:
      create: true
    monitoring:
      enabled: true
