apiVersion: v1
kind: ServiceAccount
metadata:
    name: vault-auth
    namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
    name: vault-auth-token
    namespace: kube-system
    annotations:
        kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
