apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium
  - ./storage 
  - ./vault
  - ./cert-manager
  - ./external-dns
  - ./networking # For Cloudflare Tunnel, etc.
  # - ./monitoring # Add when monitoring is set up
