apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2024.12.1"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  valuesFrom:
  - kind: Secret
    name: authentik-secrets
