apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2024.12.1"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  valuesFrom:
  - kind: Secret
    name: authentik-secrets
    valuesKey: secret_key
    targetPath: authentik.secret_key
  - kind: Secret
    name: authentik-secrets
    valuesKey: db_password
    targetPath: authentik.postgresql.password
  values:
    authentik:
      log_level: info
      postgresql:
        host: authentik-postgres-rw.authentik.svc.cluster.local
        name: authentik
        user: authentik
    postgresql:
      enabled: false
    redis:
      enabled: true
      auth:
        enabled: false
      master:
        persistence:
          storageClass: nfs-csi
    server:
      replicas: 1
      ingress:
        enabled: false
    worker:
      replicas: 1
