---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: external-dns
    namespace: external-dns
spec:
    interval: 24h
    url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns
    namespace: external-dns
spec:
    interval: 30m
    chart:
        spec:
            chart: external-dns
            version: "1.15.0"
            sourceRef:
                kind: HelmRepository
                name: external-dns
                namespace: external-dns
    values:
        sources:
            - gateway-httproute
        provider:
            name: webhook
            webhook:
                image:
                    repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
                    tag: latest
                env:
                    - name: MIKROTIK_BASEURL
                      valueFrom:
                          secretKeyRef:
                              name: mikrotik-credentials
                              key: MIKROTIK_BASEURL
                    - name: MIKROTIK_USERNAME
                      valueFrom:
                          secretKeyRef:
                              name: mikrotik-credentials
                              key: MIKROTIK_USERNAME
                    - name: MIKROTIK_PASSWORD
                      valueFrom:
                          secretKeyRef:
                              name: mikrotik-credentials
                              key: MIKROTIK_PASSWORD
                    - name: MIKROTIK_SKIP_TLS_VERIFY
                      valueFrom:
                          secretKeyRef:
                              name: mikrotik-credentials
                              key: MIKROTIK_SKIP_TLS_VERIFY
                livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8888
                    initialDelaySeconds: 10
                    periodSeconds: 10
                readinessProbe:
                    httpGet:
                        path: /readyz
                        port: 8888
                    initialDelaySeconds: 10
                    periodSeconds: 10
        policy: sync
        registry: txt
        txtOwnerId: default
