apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: bjw-s
    namespace: syncthing
spec:
    interval: 1h
    url: oci://ghcr.io/bjw-s-labs/helm
    ref:
        tag: app-template-4.5.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: syncthing
    namespace: syncthing
spec:
    interval: 30m
    chart:
        spec:
            chart: app-template
            version: "4.5.0"
            sourceRef:
                kind: OCIRepository
                name: bjw-s
                namespace: syncthing
    values:
        defaultPodOptions:
            automountServiceAccountToken: false
            securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                fsGroup: 1000
                fsGroupChangePolicy: OnRootMismatch
        controllers:
            syncthing:
                type: deployment
                replicas: 1
                annotations:
                    reloader.stakater.com/auto: "true"
                containers:
                    app:
                        image:
                            repository: syncthing/syncthing
                            tag: "1.27"
                        env:
                            TZ: UTC
                            PUID: "1000"
                            PGID: "1000"
                        probes:
                            liveness:
                                enabled: true
                                custom: true
                                spec:
                                    failureThreshold: 3
                                    httpGet:
                                        path: /rest/noauth/health
                                        port: 8384
                                    initialDelaySeconds: 0
                                    periodSeconds: 10
                                    timeoutSeconds: 1
                            readiness:
                                enabled: true
                                custom: true
                                spec:
                                    failureThreshold: 3
                                    httpGet:
                                        path: /rest/noauth/health
                                        port: 8384
                                    initialDelaySeconds: 0
                                    periodSeconds: 10
                                    timeoutSeconds: 1
                        resources:
                            requests:
                                cpu: 15m
                                memory: 150Mi
                            limits:
                                cpu: 500m
                                memory: 300Mi
                        securityContext:
                            allowPrivilegeEscalation: false
                            readOnlyRootFilesystem: true
                            capabilities:
                                drop:
                                    - ALL
        service:
            app:
                controller: syncthing
                type: ClusterIP
                ports:
                    http:
                        port: 8384
                        primary: true
            sync:
                controller: syncthing
                type: LoadBalancer
                loadBalancerIP: 192.168.1.202
                ports:
                    listen:
                        port: 22000
                        protocol: TCP
                    listen-udp:
                        port: 22000
                        protocol: UDP
                    discovery:
                        port: 21027
                        protocol: UDP
        persistence:
            config:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: syncthing-config
                globalMounts:
                    - path: /var/syncthing/config
            data:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: syncthing-data
                globalMounts:
                    - path: /var/syncthing
            tmp:
                enabled: true
                type: emptyDir
                globalMounts:
                    - path: /tmp