---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: csi-driver-nfs
    namespace: storage
spec:
    interval: 24h
    url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: csi-driver-nfs
    namespace: storage
spec:
    interval: 30m
    chart:
        spec:
            chart: csi-driver-nfs
            version: "4.6.0"
            sourceRef:
                kind: HelmRepository
                name: csi-driver-nfs
                namespace: storage
    values:
        rbac:
            create: true
        serviceAccount:
            create: true
