apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.118
  share: /srv/nfs/k8s
reclaimPolicy: Retain
mountOptions:
  - nfsvers=4.0
