---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: bjw-s
    namespace: qbittorrent
spec:
    interval: 1h
    url: oci://ghcr.io/bjw-s-labs/helm
    type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: qbittorrent
    namespace: qbittorrent
spec:
    interval: 30m
    chart:
        spec:
            chart: app-template
            version: "4.5.0"
            sourceRef:
                kind: HelmRepository
                name: bjw-s
                namespace: qbittorrent
    values:
        defaultPodOptions:
            automountServiceAccountToken: false
            securityContext:
                runAsUser: 568
                runAsGroup: 568
                runAsNonRoot: true
                fsGroup: 568
                fsGroupChangePolicy: OnRootMismatch
        controllers:
            main:
                type: deployment
                replicas: 1
                annotations:
                    reloader.stakater.com/auto: "true"
                containers:
                    main:
                        image:
                            repository: linuxserver/qbittorrent
                            tag: "4.6.7"
                        env:
                            PUID: "568"
                            PGID: "568"
                            TZ: UTC
                            WEBUI_PORT: "8080"
                        resources:
                            requests:
                                cpu: 100m
                                memory: 256Mi
                            limits:
                                cpu: 2000m
                                memory: 2Gi
        service:
            main:
                controller: main
                ports:
                    http:
                        port: 8080
            peers:
                controller: main
                type: LoadBalancer
                loadBalancerIP: 192.168.1.201
                ports:
                    peers:
                        port: 6881
                        protocol: TCP
        persistence:
            config:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: qbittorrent-config
                globalMounts:
                    - path: /config
            downloads:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: qbittorrent-downloads
                globalMounts:
                    - path: /downloads