apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "80.4.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  valuesFrom:
  - kind: Secret
    name: monitoring-secrets
  values:
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    
    prometheus:
      enabled: true
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
        
        retention: 14d
        retentionSize: 50GB
        enableAdminAPI: true
        walCompression: true
        enableFeatures:
          - memory-snapshot-on-shutdown
        
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            memory: 2000Mi
        
        externalUrl: "https://prometheus.k8s.home.lab"
        replicas: 1
        
        securityContext:
          fsGroup: 65535
          runAsNonRoot: true
          runAsUser: 65535
          runAsGroup: 65535
    
    grafana:
      enabled: true
      adminPassword: changeme
      forceDeployDashboards: true
      defaultDashboardsEnabled: true
      
      persistence:
        enabled: true
        storageClassName: nfs-csi
        size: 5Gi
      
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            access: proxy
            isDefault: true
    
    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        replicas: 1
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
    
    prometheus-node-exporter:
      enabled: true
      fullnameOverride: node-exporter
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - targetLabel: kubernetes_node
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              action: replace
              regex: (.*)
              replacement: $1
    
    kube-state-metrics:
      enabled: true
      fullnameOverride: kube-state-metrics
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - targetLabel: kubernetes_node
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              action: replace
              regex: (.*)
              replacement: $1
    
    kubeApiServer:
      enabled: true
    
    kubeControllerManager:
      enabled: true
    
    kubeScheduler:
      enabled: true
    
    kubelet:
      enabled: true
    
    coreDns:
      enabled: true
    
    defaultRules:
      create: true
      rules:
        general: true
        kubelet: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
      disabled:
        KubeControllerManagerDown: true
        KubeProxyDown: true
        KubeSchedulerDown: true
