apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "80.4.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  valuesFrom:
  - kind: Secret
    name: monitoring-secrets
    valuesKey: admin_password
    targetPath: grafana.adminPassword
  values:
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false

    prometheus:
      enabled: true
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        retention: 7d
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi

    grafana:
      enabled: true
      persistence:
        enabled: true
        storageClassName: nfs-csi
        size: 2Gi

    alertmanager:
      enabled: false

    prometheus-node-exporter:
      enabled: true

    kube-state-metrics:
      enabled: true

    kubeApiServer:
      enabled: true

    kubelet:
      enabled: true

    coreDns:
      enabled: true

    defaultRules:
      create: true
      disabled:
        KubeControllerManagerDown: true
        KubeProxyDown: true
        KubeSchedulerDown: true
        KubeSchedulerAlerting: true
