apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    interval: 30m
    timeout: 10m
    chart:
        spec:
            chart: cert-manager
            version: v1.16.0
            sourceRef:
                kind: HelmRepository
                name: jetstack
                namespace: cert-manager
            interval: 12h
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    values:
        crds:
            enabled: true
        global:
            leaderElection:
                namespace: cert-manager
